# Generated by Django 3.2.9 on 2022-10-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_forgotpswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='amount',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recharge',
            name='transactionid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
