# Generated by Django 3.2.9 on 2022-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20221001_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='chain',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
