# Generated by Django 3.2.9 on 2022-10-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_betting_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
