# Generated by Django 3.2.9 on 2022-10-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_customuser_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phoneNo',
        ),
        migrations.AlterField(
            model_name='recharge',
            name='paymentProve',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
