# Generated by Django 3.2.9 on 2022-10-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_auto_20221002_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='paymentProve',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
