# Generated by Django 3.2.9 on 2022-10-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_alter_recharge_paymentprove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='amount',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
