# Generated by Django 3.2.9 on 2022-09-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(blank=True, max_length=100)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('away', models.CharField(blank=True, max_length=100)),
                ('homeGoal', models.CharField(blank=True, max_length=100)),
                ('awayGoal', models.CharField(blank=True, max_length=100)),
                ('homeLogo', models.CharField(blank=True, max_length=100)),
                ('awaylogo', models.CharField(blank=True, max_length=100)),
                ('matchTime', models.CharField(blank=True, max_length=100)),
                ('bet1', models.CharField(blank=True, default='1 - 0', max_length=100)),
                ('bet2', models.CharField(blank=True, default='2 - 0', max_length=100)),
                ('bet3', models.CharField(blank=True, default='3 - 0', max_length=100)),
                ('bet4', models.CharField(blank=True, default='0 - 1', max_length=100)),
                ('bet5', models.CharField(blank=True, default='0 - 2', max_length=100)),
                ('bet6', models.CharField(blank=True, default='0 - 3', max_length=100)),
                ('bet7', models.CharField(blank=True, default='1 - 1', max_length=100)),
                ('bet8', models.CharField(blank=True, default='1 - 2', max_length=100)),
                ('bet9', models.CharField(blank=True, default='1 - 3', max_length=100)),
                ('bet10', models.CharField(blank=True, default='2 - 1', max_length=100)),
                ('bet11', models.CharField(blank=True, default='2 - 2', max_length=100)),
                ('bet12', models.CharField(blank=True, default='2 - 3', max_length=100)),
                ('bet13', models.CharField(blank=True, default='3 - 1', max_length=100)),
                ('bet14', models.CharField(blank=True, default='3 - 2', max_length=100)),
                ('bet15', models.CharField(blank=True, default='3 - 3', max_length=100)),
                ('odds1', models.CharField(blank=True, default='3.92', max_length=100)),
                ('odds2', models.CharField(blank=True, default='7.12', max_length=100)),
                ('odds3', models.CharField(blank=True, default='0.65', max_length=100)),
                ('odds4', models.CharField(blank=True, default='3.57', max_length=100)),
                ('odds5', models.CharField(blank=True, default='1.05', max_length=100)),
                ('odds6', models.CharField(blank=True, default='2.12', max_length=100)),
                ('odds7', models.CharField(blank=True, default='7.18', max_length=100)),
                ('odds8', models.CharField(blank=True, default='1.53', max_length=100)),
                ('odds9', models.CharField(blank=True, default='0.03', max_length=100)),
                ('odds10', models.CharField(blank=True, default='3.11', max_length=100)),
                ('odds11', models.CharField(blank=True, default='3.38', max_length=100)),
                ('odds12', models.CharField(blank=True, default='0.93', max_length=100)),
                ('odds13', models.CharField(blank=True, default='3.91', max_length=100)),
                ('odds14', models.CharField(blank=True, default='5.87', max_length=100)),
                ('odds15', models.CharField(blank=True, default='7.61', max_length=100)),
            ],
        ),
    ]
