# Generated by Django 3.2.9 on 2022-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='bet16',
            field=models.CharField(blank=True, default='4 - 3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matche',
            name='odds16',
            field=models.CharField(blank=True, default='2.03', max_length=100, null=True),
        ),
    ]
