# Generated by Django 3.2.9 on 2022-09-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20220925_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(blank=True, max_length=100)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('away', models.CharField(blank=True, max_length=100)),
                ('homeGoal', models.CharField(blank=True, max_length=100)),
                ('awayGoal', models.CharField(blank=True, max_length=100)),
                ('homeLogo', models.CharField(blank=True, max_length=100)),
                ('awaylogo', models.CharField(blank=True, max_length=100)),
                ('matchTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
