# Generated by Django 3.2.9 on 2022-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20220926_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='leagueLogo',
        ),
        migrations.RemoveField(
            model_name='market',
            name='leagueSeason',
        ),
        migrations.AddField(
            model_name='matche',
            name='leagueLogo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matche',
            name='leagueSeason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
