# Generated by Django 3.2.9 on 2022-09-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20220926_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueLogo', models.CharField(blank=True, max_length=100, null=True)),
                ('leagueSeason', models.CharField(blank=True, max_length=100, null=True)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('away', models.CharField(blank=True, max_length=100)),
                ('homeGoal', models.CharField(blank=True, max_length=100)),
                ('awayGoal', models.CharField(blank=True, max_length=100)),
                ('homeLogo', models.CharField(blank=True, max_length=100)),
                ('awaylogo', models.CharField(blank=True, max_length=100)),
                ('matchTime', models.CharField(blank=True, max_length=100)),
                ('leagueitem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='match.matche')),
            ],
        ),
    ]
