# Generated by Django 3.2.9 on 2022-09-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leagueitem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_profile', to='match.matche'),
        ),
    ]
