# Generated by Django 3.2.9 on 2022-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_matche_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetOdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(blank=True, max_length=100)),
                ('away', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
