# Generated by Django 3.2.9 on 2022-09-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20220928_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betodd',
            old_name='away',
            new_name='odds',
        ),
        migrations.RenameField(
            model_name='betodd',
            old_name='home',
            new_name='scores',
        ),
    ]
