# Generated by Django 3.2.9 on 2022-10-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_auto_20220928_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matche',
            name='awayGoal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matche',
            name='homeGoal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
