# Generated by Django 3.2.9 on 2022-10-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20221001_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='finalscores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
